=== tombelial666/clinicproject/bin/XSD/createServiceResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema 

xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://org.example/createServiceResponse" 
xmlns:resp="http://org.example/createServiceResponse" 
xmlns:tns="http://org.example/service"
elementFormDefault="qualified">

  <import namespace="http://org.example/service" schemaLocation="Service.xsd"/>

<element name="CreateServiceResponse"
	     type="resp:CreateServiceResponse"/>

<complexType name="CreateServiceResponse">

		<sequence>
		<element name="responseStatus" type="tns:rResponseStatus"/>
		<element name="appointmentTime" type="tns:rAppointmentTime"/>
		<element name="roomNumber" type="tns:rRoomNumber"/>
        <element name="serviceID" type="tns:rServiceID"/>
        <element name="docName" type="tns:rDocName"/>
        <element name="price" type="tns:rPrice"/>
        <element name="orderID" type="tns:rOrderID"/>
        </sequence>
        
</complexType>

</schema>

=== tombelial666/clinicproject/bin/XSD/createServiceResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<resp:CreateServiceResponse xmlns:resp="http://org.example/createServiceResponse" xmlns:tns="http://org.example/service" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://org.example/createServiceResponse createServiceResponse.xsd ">
  <resp:responseStatus>SUCCESS</resp:responseStatus>
  <resp:appointmentTime>2021-12-31T12:00:00</resp:appointmentTime>
  <resp:roomNumber>1</resp:roomNumber>
  <resp:serviceID>1</resp:serviceID>
  <resp:docName>resp:docName</resp:docName>
  <resp:price>999999.19</resp:price>
  <resp:orderID>0</resp:orderID>
</resp:CreateServiceResponse>
