=== tombelial666/clinicproject/bin/XSD/getDocsServiceResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema 

xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://org.example/getDocsServiceResponse" 
xmlns:resp="http://org.example/getDocsServiceResponse" 
xmlns:tns="http://org.example/service"
elementFormDefault="qualified">

  <import namespace="http://org.example/service" schemaLocation="Service.xsd"/>

<element name="GetDocsServiceResponse"
	     type="resp:GetDocsServiceResponse"/>

<complexType name="GetDocsServiceResponse">

     <sequence>
        <element name="serviceID" type="tns:rServiceID"/>
        <element name="docName" type="tns:rDocName"/>
        <element name="serviceName" type="tns:rServiceName"/>
        <element name="price" type="tns:rPrice"/>
        <element name="docSFreeTime" type="tns:rDocsFreeTime"/>
        <element name="roomNumber" type="tns:rRoomNumber"/>
        <element name="medicalSpeciality" type="tns:rMedicalSpeciality"/>
        <element name="responseStatus" type="tns:rResponseStatus"/>
      </sequence>

</complexType>

</schema>

=== tombelial666/clinicproject/bin/XSD/getDocsServiceResponse.xml
<?xml version="1.0" encoding="UTF-8"?>

<resp:GetDocsServiceResponse 

xmlns:resp="http://org.example/getDocsServiceResponse" 
xmlns:tns="http://org.example/service" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://org.example/getDocsServiceResponse getDocsServiceResponse.xsd ">

  <resp:serviceID>1</resp:serviceID>
  <resp:docName>resp:docName</resp:docName>
  <resp:serviceName>resp:serviceName</resp:serviceName>
  <resp:price>0.0</resp:price>
  <resp:docSFreeTime>2021-12-31T12:00:00</resp:docSFreeTime>
  <resp:roomNumber>0</resp:roomNumber>
  <resp:medicalSpeciality>resp:medicalSpeciality</resp:medicalSpeciality>
  <resp:responseStatus>SUCCESS</resp:responseStatus>
  
</resp:GetDocsServiceResponse>
