=== tombelial666/clinicproject/bin/XSD/getServiceResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://org.example/getServiceResponse" 
xmlns:resp="http://org.example/getServiceResponse" 
xmlns:tns="http://org.example/service"
elementFormDefault="qualified">

  <import namespace="http://org.example/service" 
  schemaLocation="Service.xsd"/>
  
  <element name="getServiceResponse" type="resp:getServiceResponse"></element>
  
      <complexType name="getServiceResponse">
        <sequence>
            <element name="serviceID" type="tns:rServiceID" maxOccurs="1"/>
            <element name="docName" type="tns:rDocName" maxOccurs="1"/>
            <element name="medicalSpecaiality" type="tns:rMedicalSpeciality"/>
            <element name="serviceName" type="tns:rServiceName" maxOccurs="1"/>
            <element name="price" type="tns:rPrice" maxOccurs="1"/>
            <element name="roomNumber" type="tns:rRoomNumber" minOccurs="0"/>
            <element name="docSFreeTime" type="tns:rDocsFreeTime" maxOccurs="1"/>
            <element name="responseStatus" type="tns:rResponseStatus"/>
        </sequence>
    </complexType>
  
</schema>

=== tombelial666/clinicproject/bin/XSD/getServiceListResponse.xml
<?xml version="1.0" encoding="UTF-8"?>

<resp:getServiceResponse 

xmlns:resp="http://org.example/getServiceResponse" 
xmlns:tns="http://org.example/service" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://org.example/getServiceResponse getServiceResponse.xsd ">

  <resp:serviceID>5</resp:serviceID>
  <resp:docName>resp:docName</resp:docName>
  <resp:medicalSpecaiality>resp:medicalSpecaiality</resp:medicalSpecaiality>
  <resp:serviceName>resp:serviceName</resp:serviceName>
  <resp:price>0.0</resp:price>
  <resp:docSFreeTime>2021-12-31T12:00:00</resp:docSFreeTime>
  <resp:responseStatus>SUCCESS</resp:responseStatus>
  
</resp:getServiceResponse>
