=== tombelial666/clinicproject/src/XSD/getServiceListRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://org.example/getServiceListRequest" 
xmlns:req="http://org.example/getServiceListRequest" 
xmlns:tns="http://org.example/service"
elementFormDefault="qualified">

  <import namespace="http://org.example/service" schemaLocation="Service.xsd"/>


<element name="GetServiceListRequest"
             type="req:GetServiceListRequest"/>

    <complexType name="GetServiceListRequest">
     <sequence>
        <element name="serviceID" type="tns:rServiceID"/>
        <element name="docName" type="tns:rDocName"/>
        <element name="serviceName" type="tns:rServiceName"/>
        <element name="price" type="tns:rPrice"/>
        <element name="docSFreeTime" type="tns:rDocsFreeTime"/>
        <element name="roomNumber" type="tns:rRoomNumber"/>
        <element name="medicalSpeciality" type="tns:rMedicalSpeciality"/>
        <element name="responseStatus" type="tns:rResponseStatus"/>
      </sequence>
    </complexType>
    
    </schema>

=== tombelial666/clinicproject/src/XSD/getServiceListRequest.xml
<?xml version="1.0" encoding="UTF-8"?>

<req:GetServiceListRequest 

xmlns:req="http://org.example/getServiceListRequest" 
xmlns:tns="http://org.example/service" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://org.example/getServiceListRequest getServiceListRequest.xsd ">

  <req:serviceID>1</req:serviceID>
  <req:docName>req:docName</req:docName>
  <req:serviceName>req:serviceName</req:serviceName>
  <req:price>0.0</req:price>
  <req:docSFreeTime>2021-12-31T12:00:00</req:docSFreeTime>
  <req:roomNumber>0</req:roomNumber>
  <req:medicalSpeciality>req:medicalSpeciality</req:medicalSpeciality>
  <req:responseStatus>SUCCESS</req:responseStatus>

</req:GetServiceListRequest>
